behaviors:
  SnakeAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 40960
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear

    network_settings:
      normalize: true   
      hidden_units: 256
      num_layers: 3

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail: 
        strength: 0.7
        demo_path: DemoArcticSnake/ArcticSnake4.demo
    behavioral_cloning:
      strength: 0.7
      demo_path: DemoArcticSnake/ArcticSnake4.demo

    max_steps: 500000
    time_horizon: 64
    summary_freq: 1000
